version: '3.8'
services:
  moviebookingdb:
    image: mongo
    container_name: moviebookingdb
    ports:
      - 0.0.0.0:27017:27017
    networks:
      - MOVIEBOOKING
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    networks:
      - MOVIEBOOKING
    links:
      - moviebookingdb:mongo
    ports:
      - 0.0.0.0:8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_ENABLEADMIN: true
      ME_CONFIG_MONGODB_AUTHDATABASE: ${MONGODB_AUTHENTICATION_DB}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: moviebookingdb
    depends_on:
      - moviebookingdb
networks:
  MOVIEBOOKING:
    name: MOVIEBOOKING
volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
      