global:
  scrape_interval: 15s
scrape_configs:
- job_name: movie-booking-app-metrics
  metrics_path: /actuator/prometheus
  scrape_interval: 5s
  static_configs:
  - targets: ['host.docker.internal:8088']
    labels:
      application: Movie Booking Application
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090